version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: '18'
  build:
    commands:
      - echo Installing source NPM dependencies.
      - export DB_PASSWORD=$(aws secretsmanager get-secret-value --secret-id ${DB_PASSWORD_KEY} --query SecretString --output text | jq -r '.password')
      - node --version # print the version for logging
      - npm --version # print the version for logging
      - if [ ! -d "node_modules" ]; then npm install; fi  # ✅ Install only if node_modules doesn't exist
      - npm run build
      - echo Running build...
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
