export const campaignTemplateDefaults = {
    Campaign: '',
    'Campaign Type': 'Search',
    Networks: 'Google search',
    Budget: '10',
    'Budget type': 'Daily',
    'Standard conversion goals': 'Account-level',
    'Customer acquisition': 'Bid equally',
    Languages: 'en',
    'Bid Strategy Type': 'Maximize conversions',
    'Bid Strategy Name': '',
    'Target CPA': '5',
    'Broad match keywords': 'Off',
    'Ad Schedule': '[]',
    'Ad rotation': 'Optimize for clicks',
    'Content exclusions': '[]',
    'Targeting method': 'Location of presence',
    'Exclusion method': 'Location of presence',
    'Audience targeting': 'Audience segments',
    'Flexible Reach': 'Audience segments',
    'Campaign Status': 'Paused'
  }

  export const adGroupTemplateDefaults = {
    Campaign: '',
    'Ad Group': '',
    Labels: '',
    'Max CPC': '0.01',
    'Max CPM': '0.01',
    'Target CPA': '',
    'Max CPV': '0.01',
    'Target CPV': '',
    'Percent CPC': '0.01',
    'Target CPM': '',
    'Target ROAS': '',
    'Desktop Bid Modifier': '',
    'Mobile Bid Modifier': '',
    'Tablet Bid Modifier': '',
    'TV Screen Bid Modifier': '',
    'Display Network Custom Bid Type': 'None',
    'Optimized targeting': 'Disabled',
    'Strict age and gender targeting': 'Disabled',
    'Ad rotation': '',
    'Ad Group Type': 'Standard',
    Languages: 'All',
    'Audience targeting': 'Audience segments',
    'Audience name': '',
    'Age demographic': '',
    'Gender demographic': '',
    'Income demographic': '',
    'Parental status demographic': '',
    'Remarketing audience segments': '',
    'Interest categories': '',
    'Life events': '',
    'Custom audience segments': '',
    'Detailed demographics': '',
    'Remarketing audience exclusions': 'Audience segments;Genders;Ages;Parental status;Household incomes',
    'Flexible Reach': '',
    'Tracking template': '',
    'Final URL suffix': '',
    'Custom parameters': '',
    'Campaign Status': 'Paused',
    'Ad Group Status': 'Enabled',
    Comment: ''
  }

  
export const adsTemplateDefaults = {
    Campaign: '',
    'Ad Group': '',
    'Ad type': 'Responsive search ad',
    Labels: '',
    'Headline 1': '',
    'Headline 1 position': '',
    'Headline 2': '',
    'Headline 2 position': '',
    'Headline 3': '',
    'Headline 3 position': '',
    'Headline 4': '',
    'Headline 4 position': '',
    'Headline 5': '',
    'Headline 5 position': '',
    'Headline 6': '',
    'Headline 6 position': '',
    'Headline 7': '',
    'Headline 7 position': '',
    'Headline 8': '',
    'Headline 8 position': '',
    'Headline 9': '',
    'Headline 9 position': '',
    'Headline 10': '',
    'Headline 10 position': '',
    'Headline 11': '',
    'Headline 11 position': '',
    'Headline 12': '',
    'Headline 12 position': '',
    'Headline 13': '',
    'Headline 13 position': '',
    'Headline 14': '',
    'Headline 14 position': '',
    'Headline 15': '',
    'Headline 15 position': '',
    'Description 1': '',
    'Description 1 position': '',
    'Description 2': '',
    'Description 2 position': '',
    'Description 3': '',
    'Description 3 position': '',
    'Description 4': '',
    'Description 4 position': '',
    'Path 1': '',
    'Path 2': '',
    'Final URL': '',
    'Campaign Status': 'Paused',
    'Ad Group Status': 'Enabled',
    Status: 'Enabled'
  }
  
  export const keywordTemplateDefaults = {
    Campaign: '',
    'Ad Group': '',
    Keyword: '',
    'Criterion Type': 'Exact',
    'Campaign Status': 'Paused',
    'Ad Group Status': 'Enabled',
    Status: 'Enabled',
    'Approval Status': 'Approved',
    Comment: ''
  }
  